name: task_chase
description: "task chase app for austec"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  device_preview: ^1.2.0
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  step_progress_indicator: ^1.0.2
  flutter_chat_ui: ^1.6.14
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  file_picker: ^8.0.5
  chat_bubbles: ^1.6.0
  slide_switcher: ^1.1.2
  adaptive_action_sheet: ^2.0.3
  mongo_dart: ^0.10.3
  form_validator: ^2.1.1
  connectivity_plus: ^5.0.1
  http: ^1.2.1
  quickalert: ^1.1.0
  loading_animation_widget: ^1.2.1
  country_picker: ^2.0.26

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
  - assets/images/
  - assets/logos/
  - assets/fonts/
  - assets/icons/
  - assets/images/onboard_images/
  - assets/images/start_screen/
  - assets/logos/social_buttons/
  - assets/images/success_screen/reset_password/
  - assets/images/success_screen/send_email/
  - assets/images/add_project/
  - assets/images/client_profile/
  - assets/icons/client_about_page/
  - assets/icons/client_payment_page/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets\fonts\inter.ttf
      
    